name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest and coverage
        run: |
          pytest --cov=. --cov-report=xml
      - name: Check coverage and set job outcome
        run: |
          coverage=$(python -c "import xml.etree.ElementTree as E; cov=E.parse('coverage.xml').getroot().find('totals').get('percent'); print(cov)")
          if (( $(echo "$coverage >= 75" | bc -l) )); then echo "Coverage is above 75%. Job passed."; else echo "Coverage is below 75%. Job failed."; exit 1; fi
